---
# Define supported platforms
hpv_libvirt_server_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
hpv_libvirt_server_os_family: |
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

# Define common paths
hpv_libvirt_server_base_common:
  access:
    owner: "root"
    group: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates:
    libvirtd_conf: "libvirtd.conf.j2"
    qemu_conf: "qemu.conf.j2"

# Define subsystem server options. This will be used along with hpv_libvirt_server_server_options
hpv_libvirt_server_server_presets:
  firewall:
    zone: "public"
    rule_id: "libvirt_remote_access"

hpv_libvirt_server_alert_ansible_managed_file: "Warning: This file is automatically generated by the Ansible Role: serdigital64.hypervisor.hpv_libvirt_server. Do not modify."
...
