---
galaxy_info:
  role_name: "hpv_libvirt_client"
  author: "serdigital64"
  description: "Manage provisioning of LibVirt client"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "libvirt"
    - "client"
dependencies: []
...
