---
- name: "Hypervisor / LibVirt / Server / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ hpv_libvirt_server_application }}"
    sys_package_profiles: "{{ hpv_libvirt_server_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
