---
- name: "Hypervisor / LibVirt / Server / Setup / Firewall / Configure remote management"
  vars:
    sec_firewall_os:
      setup: true
    sec_firewall_os_rules:
      - id: "{{ hpv_libvirt_server_server_presets['firewall']['rule_id'] }}"
        zone: "{{ hpv_libvirt_server_server_presets['firewall']['zone'] }}"
        port: "{{ hpv_libvirt_server_server_options['tcp_access']['port'] }}/tcp"
        allow: "{{ hpv_libvirt_server_server_options['tcp_access']['enabled'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.sec.sec_firewall_os"
...
