---
- name: "Hypervisor / LibVirt / Server / Setup / Server / Configure libvirtd daemon"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ hpv_libvirt_server_base['access']['owner'] }}"
    group: "{{ hpv_libvirt_server_base['access']['group'] }}"
    mode: "{{ hpv_libvirt_server_base['access']['mode']['file'] }}"
    src: "{{ hpv_libvirt_server_base['templates']['libvirtd_conf'] }}"
    dest: "{{ hpv_libvirt_server_base['files']['libvirtd_conf'] }}"

- name: "Hypervisor / LibVirt / Server / Setup / Server / Configure qemu options"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ hpv_libvirt_server_base['access']['owner'] }}"
    group: "{{ hpv_libvirt_server_base['access']['group'] }}"
    mode: "{{ hpv_libvirt_server_base['access']['mode']['file'] }}"
    src: "{{ hpv_libvirt_server_base['templates']['qemu_conf'] }}"
    dest: "{{ hpv_libvirt_server_base['files']['qemu_conf'] }}"
...
