---
- name: "Hypervisor / LibVirt / Server / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in hpv_libvirt_server_platforms

- name: "Hypervisor / LibVirt / Server / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "Hypervisor / LibVirt / Server / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "hpv_libvirt_server_prerequisite.yml"
  when:
    - "'resolve_prereq' in hpv_libvirt_server"
    - hpv_libvirt_server['resolve_prereq']
...
