---
- name: "Hypervisor / LibVirt / Server / Prepare / Kernel / Enable IP Forwarding"
  vars:
    sys_kernel:
      setup: true
    sys_kernel_tunables:
      net:
        ipv4:
          ip_forward: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_kernel"
...
