---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        hpv_libvirt_client:
          deploy: true
        hpv_libvirt_client_application:
          bin:
            name: "libvirt"
            type: "distro"
            version: "latest"
            installed: true
          dev:
            name: "libvirt_dev"
            type: "distro"
            version: "latest"
            installed: true
      ansible.builtin.include_role:
        name: "hpv_libvirt_client"
...
