---
- name: "Hypervisor / LibVirt / Client / Initialize"
  ansible.builtin.include_tasks:
    file: "hpv_libvirt_client_initialize.yml"

- name: "Hypervisor / LibVirt / Client / Deploy"
  ansible.builtin.include_tasks:
    file: "hpv_libvirt_client_deploy.yml"
  when:
    - "'deploy' in hpv_libvirt_client"
    - hpv_libvirt_client['deploy']

- name: "Hypervisor / LibVirt / Client / Finalize"
  ansible.builtin.include_tasks:
    file: "hpv_libvirt_client_finalize.yml"
...
