---
- name: "Verify"
  hosts: linux-systemd
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "hpv_libvirt_server"

    - name: "Identify service status"
      ansible.builtin.command:
        argv:
          - "/usr/bin/systemctl"
          - "is-active"
          - "{{ hpv_libvirt_server_subsystem_profile['service'] }}"
      changed_when: false
      register: result

    - name: "Check that the service is active"
      ansible.builtin.assert:
        that:
          - result['stdout_lines'] is search( 'active' )
...
